<?php
/**
 * Created by PhpStorm.
 * UserType: osboxes
 * Date: 12/11/17
 * Time: 10:36
 */

namespace app\api\controllers;
use app\models\GradeData;
use yii\filters\AccessControl;
use yii\mongodb\Query;
use yii\rest\ActiveController;
use yii\web\Controller;
use yii\web\Response;

class GradesController extends Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'only' => ['index', 'view'],
            'rules' => [
                [
                    'allow' => true,
                    'actions' => ['index', 'view'],
                    'roles' => ['?'],
                ]
            ],
        ];
        return $behaviors;
    }

    public function actionIndex() {
        $grades_info = GradeData::getGradeInfo();

        foreach($grades_info as $key => $grade) {
            $query = new Query();
            $count = $query
                ->from('tests')
                ->filterWhere(['field' => 'math', 'grade' => $key])
                ->count();

            $grades_info[$key]['subjects'] = [
                'math' => $count
            ];
        }

        $response = \Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = [
            'success' => true,
            'data' => $grades_info
        ];

        return $response;
    }

    public function actionView($grade) {
        $grades_info = GradeData::getGradeInfo();

        $response = \Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = [
            'success' => true,
            'data' => $grades_info[$grade]
        ];

        return $response;
    }
}