<?php
/**
 * Created by PhpStorm.
 * UserType: osboxes
 * Date: 13/11/17
 * Time: 18:35
 */

namespace app\api\controllers;


use app\models\Test;
use app\models\TestSession;
use \DateTime;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;
use yii\web\Response;

class TestSessionsController extends ActiveController
{
    public $modelClass = 'app\models\TestSession';

    public function actions()
    {
        $actions = parent::actions();

        // disable the "delete" and "update", "options" actions
        unset($actions['create'], $actions['update'], $actions['delete']);

        return $actions;
    }

    public function actionCreate() {
        $request = \Yii::$app->request;
        $test_id = $request->post('test_id');

        if(!$test_id)
            return [
                'success' => false,
                'message' => 'TestType id is required'
            ];

        $provider = new ActiveDataProvider([
            'query' => Test::find()->where(['id' => intval($test_id)])
        ]);
        $models = $provider->getModels();

        if(count($models) == 0) {
            return [
                'success' => false,
                'message' => 'TestType was not found'
            ];
        }

        $test = $models[0];

        $model = new TestSession();
        $model->test_id = $test_id;
        $model->difficulty = $test['difficulty'];

        $model->start_at = (new DateTime())->getTimestamp();
        $model->score = 0;
        $model->questions = [];
        $model->open_question = 1;
        $model->num_questions = 10;

        $model->save();

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'success' => true,
            'data' => $model
        ];
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}